site_name: Billing Api Documentation

repo_url: https://github.com/uniclab-01/billing-api

theme:
  name: material

#plugins:
#  - mkdocstrings:
#    handlers:
#      custom_handler:
#        handler_config_option:
#          yes
#        options:
#          some_config_option: "a"
#          other_config_option: 0
extra:
  search:
  language: 'en, ru'

nav:
  - Home:
      index.md
  - Billing api:
      billing_api_sdk.md
