site_name: Billing Api Documentation

repo_url: https://github.com/uniclab-01/billing-api

theme:
  name: material

plugins:
 - mkdocstrings:
    handlers:
      - search.index
      - markdown.typed_ast

extra:
  search:
  language: 'en, ru'

nav:
  - Home:
      index.md
  - Billing api:
      billing_api_sdk.md
