site_name: Billing Api Documentation

repo_url: https://github.com/uniclab-01/billing-api

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings

extra:
  search:
  language: 'en, ru'

nav:
  - Home:
      index.md
  - Billing api:
      billing_api_sdk.md
